### ISSUE TITLE
blo install <package>  results in: ERROR -- : Actor crashed!

### ISSUE THREAD

**Issue by donbecker** [reset/berkflow#7]
Berksflow uploads all cookbooks in the package correctly.

blo v0.6.2
chefdk v0.3.2

However after succeeding, there is an error: 

Uploaded 24 cookbooks.
Done.
E, [2014-11-18T17:27:38.350779 #35613] ERROR -- : Actor crashed!
RuntimeError: a group member went missing. This shouldn't be!
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/supervision_group.rb:103:in `restart_actor'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:15:in`block in call'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in`block in task'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in`block in create'

**Comment by DPD-30** [comment]
BUMP.  I am using BLO 0.6.4 and still seeing this error.

**Comment by jasonwbarnett** [comment]
bump. using the latest version of the ChefDK and I still get this error.

**Comment by reset** [comment]
@jasonwbarnett @DPD-30 see my previous comment. This is not a real error in execution - it is an overly noisy logging message with the underlying concurrency library when actors attempt to shutdown. 

@donbecker We can't disable the logger or suppress this without intercepting every logging message and removing these.

There is no updated version of Celluloid which addresses this issue. You can safely ignore these messages. They will go away once the issue is fixed in Celluloid or if Celluloid is dropped as a dependency.
